leftnav:
- identifier: 18b8242e-6a69-a8fe-8104-4a564d2c2037
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 0c293eca-fd14-6f0f-b404-eeeb89743809
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 48e1f949-ef2c-c114-6b8f-a7c4f1f23a65
  name: Assignments
  pageRef: /pages/assignments
  weight: 30
- identifier: 3164cd9e-2917-4ebf-967d-4b001fa64ce2
  name: Projects
  pageRef: /pages/projects
  weight: 40
- identifier: 8d033ea2-80b5-83ab-6a92-0f16d036220c
  name: Tools
  pageRef: /pages/tools
  weight: 50
- identifier: b71c5203-694d-2da0-0b0e-0334146f7b1a
  name: Study Materials
  pageRef: /pages/study-materials
  weight: 60
- identifier: 2780c5cf-80f2-789b-9170-8742a5e11d9c
  name: Readings
  pageRef: /pages/readings
  weight: 70
